### ISSUE TITLE
Build for aarch and aarch64 (32-bit ARM and 64-bit ARM)

### ISSUE THREAD

**Issue by probonopd** [probonopd/static-tools#11]
* https://github.com/uraimo/run-on-arch-action
* https://github.com/jnwatson/py-lmdb/blob/18071c9f11ff153ca04c9c8349523bb877305d19/.github/workflows/python-package.yml#L184
* https://github.com/multiarch/qemu-user-static

**Comment by Tachi107** [comment]
Still searching... Also found this: https://github.com/docker/setup-qemu-action

**Comment by probonopd** [comment]
For future reference, RISCV:
* https://github.com/uraimo/run-on-arch-action/issues/28
* https://github.com/uraimo/run-on-arch-action/pull/49
