### ISSUE TITLE
patchelf is not built for all architectures

### ISSUE THREAD

**Issue by probonopd** [probonopd/static-tools#16]
patchelf is missing for 32-bit ARM and 64-bit ARM. Why?
And why does that not result in a "red" build?

**Comment by Tachi107** [comment]
https://github.com/probonopd/static-tools/pull/12#issue-1221941183

> Then I removed patchelf from the build because it seems that it was only used by the shared appstreamcli build. Please correct me if I'm wrong.

**Comment by probonopd** [comment]
Please reinstate patchelf. We need it in various places. Thanks!

**Comment by probonopd** [comment]
Reference:
https://github.com/NixOS/patchelf/issues/185
