### ISSUE TITLE
Alpine provides many static libraries that are already static, like: gettext-static.

### ISSUE THREAD

**Issue by xplshn** [probonopd/static-tools#49]
Most -dev packages also have a static cousin under the same name but with the -static preffix. Why are we not using that? Around 400 packages in the repos (edge+community+edge+main+edge+testing) are static libraries

**Comment by probonopd** [comment]
Are we not using those? Can you give a concrete example of what could be improved where please?

**Comment by xplshn** [comment]
Here: https://github.com/probonopd/static-tools/blob/master/build.sh#:~:text=apk%20add%20eudev%2Ddev-,gettext%2Ddev,-linux%2Dheaders%20meson%20%23

should install gettext-static too, also, have you tried libudev-zero? Its a library that's a drop-in replacement for eudev, instead of being a daemon, its a library.
